{% set name = "cligv" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jonasfreudig/{{ name }}/archive/v{{ version }}.tar.gz
  # sha256: will need to be updated once i have a release

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cligv = cligv.cli:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=42
    - wheel
  run:
    - python >=3.7
    - pysam >=0.19.0
    - rich >=10.0.0

test:
  imports:
    - cligv
  commands:
    - pip check
    - cligv --version
  requires:
    - pip

about:
  home: https://github.com/jonasfreudig/cligv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'command line Interactive Genome Viewer'
  description: |
    clIGV (command line Interactive Genome Viewer) is a fast, interactive 
    genome browser for the terminal. It allows visualization of genomic 
    sequences, variants from VCF files, and alignments from BAM files, 
    all with an intuitive interface directly in your terminal.
  dev_url: https://github.com/jonasfreudig/cligv

extra:
  recipe-maintainers:
    - jonasfreudig